services:
  agent:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TOR_PASSWORD=${TOR_PASSWORD}
      - AGENT_EMAIL=${AGENT_EMAIL}
  
  agent-windows:
    build:
      context: .
      dockerfile: Dockerfile.windows
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - TOR_PASSWORD=${TOR_PASSWORD}
      - AGENT_EMAIL=${AGENT_EMAIL}
    profiles:
      - windows
